#!/bin/bash

flex hw1.lex
gcc -ll hw1.yy.c
./a.out < /home/talhassid/046266/example/example2-err.cmm > hw1-err.res  
sdiff hw1-err.res /home/talhassid/046266/example/example2-err.tokens
./a.out < example/example.cmm >& hw1.res  
sdiff hw1.res example/example.tokens 


